#!/bin/sh
# Snapshot the fp issue tracker into a committed markdown file.
#
#     sh data-raw/snapshot-tracker.sh
#
# Why this exists. `.fp/` is gitignored (.gitignore:38, and .Rbuildignore
# carries ^\.fp$ so it never reaches R CMD check either), so the tracker is a
# local SQLite database that no commit, no bundle and no clone has ever
# contained. That is a problem specific to this project rather than a general
# one: docs/architecture.md cites RADD-* issue ids as the evidence behind its
# decisions -- section 10's open-items table alone names more than twenty -- and
# the reasoning those ids point at lives in issue comments, not in code. Lose
# .fp/ and every one of those citations dangles while the code survives intact.
#
# The same gap was found from the outside first: the O12 row records that rurl's
# .fp/ is gitignored too, which is why a report filed there exists in no git
# history anywhere. This script is that finding applied to raddr itself.
#
# It is deliberately a snapshot and not a sync. fp stays the working tracker --
# nothing here is meant to be read in preference to `fp context <id>`, and
# nothing reads this file back. It exists so the narrative survives the disk.
#
# GENERATED OUTPUT, OVERWRITTEN WHOLESALE. Hand-edits to the output file are
# lost on the next run. This is the hazard open item O10 turned up with
# inst/NOTICE, where build-registry.R silently deleted an appended licence
# notice, so the output carries the same warning in its own header.
#
# Issues are emitted in sorted short-id order rather than tree or creation
# order, so that regenerating produces a minimal diff: a new comment changes one
# stanza instead of reshuffling the file.
set -eu

OUT="docs/tracker-snapshot.md"

if ! command -v fp >/dev/null 2>&1; then
	echo "fp not found on PATH; cannot snapshot the tracker" >&2
	exit 1
fi

if [ ! -d .fp ]; then
	echo "no .fp/ directory here; run this from the repository root" >&2
	exit 1
fi

# Short ids, sorted, so the output order is stable across runs.
ids=$(fp issue list --format json | python3 -c '
import json, sys
d = json.load(sys.stdin)
for s in sorted(i["shortId"] for i in d["issues"]):
    print(s)
')

count=$(printf "%s\n" "$ids" | grep -c .)

{
	echo "# fp tracker snapshot"
	echo
	echo "**Generated by \`data-raw/snapshot-tracker.sh\` on $(date +%Y-%m-%d).**"
	echo "$count issues. Do not hand-edit: the next run overwrites this file"
	echo "wholesale, exactly as \`build-registry.R\` overwrites \`inst/NOTICE\`."
	echo
	echo "\`.fp/\` is gitignored, so this file is the only copy of the tracker in"
	echo "git. It is a backstop for the RADD-* citations in"
	echo "\`docs/architecture.md\`, not a replacement for the tracker: \`fp\` remains"
	echo "authoritative and \`fp context <id>\` remains the way to read an issue."
	echo
	echo "## Hierarchy"
	echo
	echo '```'
	fp tree
	echo '```'
	echo
	echo "## Issues"
	echo
	echo "$count stanzas, in sorted short-id order. Each is \`fp context\` output"
	echo "with its headings demoted one level."
	echo

	for s in $ids; do
		# Demote every ATX heading one level so the per-issue h1 becomes an h2
		# and nests under "## Issues" instead of competing with the title.
		fp context "RADD-$s" | sed 's/^#/##/'
		echo
	done
} >"$OUT.tmp"

# Collapse the trailing blank lines the per-issue loop leaves behind. Without
# this the pre-commit end-of-file-fixer rewrites the file after it is generated,
# so the next run would report a diff against a tree that was already committed
# and the snapshot would never look clean twice in a row.
python3 -c '
import sys
p = sys.argv[1]
with open(p, encoding="utf-8") as f:
    text = f.read()
with open(p, "w", encoding="utf-8") as f:
    f.write(text.rstrip("\n") + "\n")
' "$OUT.tmp"

mv "$OUT.tmp" "$OUT"

echo "wrote $OUT ($count issues, $(wc -c <"$OUT" | tr -d ' ') bytes)"
