# The vendored IANA special-purpose registries.
# See docs/architecture.md sections 7 and 5.3.
#
# The data is generated by data-raw/build-registry.R into R/sysdata.rda. Nothing
# here reads a file, and nothing here touches the network: raddr ships the
# registry rather than fetching it, so that "performs no network access" is a
# property of the code and not of a default argument (section 7).

# The public columns. `w1`-`w4` are the matcher's storage, not part of the
# answer, so they stay internal and the exported table keeps the block text and
# prefix length -- the two forms a caller can actually read.
registry_public_columns <- c(
  "block", "space", "prefix_len", "name", "rfc",
  "allocation_date", "termination_date",
  "source", "destination", "forwardable", "globally_reachable",
  "reserved_by_protocol", "footnotes"
)

#' The bundled IANA special-purpose address registries
#'
#' Returns the two IANA special-purpose address registries as one data frame,
#' exactly as vendored. This is the table `addr_classify()` will match against.
#' (Not a link: `addr_classify()` arrives with the classification layer.)
#'
#' @section All five policy columns, never collapsed:
#'
#' IANA records five independent properties per block, and raddr surfaces all
#' five rather than reducing them to a single "is it private" flag.
#' `globally_reachable` **is** IANA's `Globally Reachable` column, per row, with
#' an RFC citation -- not a value raddr derives.
#'
#' Each is `logical`, and `NA` is a real answer with a real meaning: IANA
#' declined to give one. Two cases produce it.
#'
#' \describe{
#'   \item{The block is deprecated}{`192.88.99.0/24` and `2001:10::/28` carry a
#'     `termination_date` and no policy values at all.}
#'   \item{The answer depends on something the table cannot express}{Teredo
#'     (`2001::/32`) and 6to4 (`2002::/16`) are both recorded as `N/A` for
#'     `globally_reachable` -- but for **two different reasons**, carrying two
#'     different IANA footnotes. Do not merge them.}
#' }
#'
#' The two `N/A` reasons, kept apart because a reader following either
#' footnote must find the reason raddr states:
#'
#' \describe{
#'   \item{6to4 (`2002::/16`), footnote `[3]`, RFC 3056}{reachability follows
#'     the *embedded* IPv4 address, which a prefix table cannot express.}
#'   \item{Teredo (`2001::/32`), footnote `[2]`, RFC 4380 section 5}{a
#'     different thing entirely: relay advertisement is **voluntary and
#'     per-deployment**, so whether any given Teredo address is reachable
#'     depends on what its operator chose to advertise -- not on the embedded
#'     client address.}
#' }
#'
#' Reading either as `FALSE` would assert a policy IANA specifically withheld,
#' so raddr keeps them `NA`.
#'
#' @section Blocks, not rows:
#'
#' One row here is one prefix. That is not always one row upstream: the CSV
#' names two prefixes in a single record (`192.0.0.170/32, 192.0.0.171/32`),
#' and three records wrap across lines because they cite more than one RFC.
#' The vendored 25 + 25 records become **51 blocks**.
#'
#' @section Longest prefix, not first match:
#'
#' The registry contains deliberate carve-outs -- `192.0.0.9/32` and
#' `192.0.0.10/32` are globally reachable inside a `192.0.0.0/24` that is not.
#' Any lookup over this table must be longest-prefix-match.
#'
#' @section Footnotes:
#'
#' `footnotes` records which upstream footnote markers a row carried, as a
#' space-separated string, and is `""` when it carried none. The footnote
#' **text** is not in the CSV -- it lives on the registry page -- so raddr
#' reports that a caveat exists rather than inventing its wording.
#'
#' @return A data frame of 51 rows. See the sections above for the columns.
#'
#' @seealso [addr_registry_version()] for the snapshot's provenance.
#'
#' @examples
#' reg <- addr_registry()
#' nrow(reg)
#'
#' # The carve-out that forces longest-prefix matching
#' reg[startsWith(reg$block, "192.0.0."), c("block", "globally_reachable")]
#'
#' # The blocks whose reachability IANA declined to state
#' reg[is.na(reg$globally_reachable), c("block", "name", "termination_date")]
#'
#' @export
addr_registry <- function() {
  raddr_registry_data$blocks[registry_public_columns]
}

address_space_public_columns <- c(
  "block", "space", "prefix_len", "name", "rfc",
  "status", "date", "notes", "footnotes"
)

#' The bundled IANA address-space registries
#'
#' Returns the IANA IPv4 and IPv6 Address Space registries as one data frame,
#' exactly as vendored. This is the **fallback** layer: it answers what a range
#' is for and who holds it, for every address, including the ranges the
#' special-purpose registries never mention.
#'
#' @section Why a second pair of registries:
#'
#' Each of these two registries is an **exact partition** of its address space
#' -- 256 IPv4 `/8`s and 20 IPv6 blocks that tile `::/0` with no gap and no
#' overlap, asserted at build time. Together with [addr_registry()] that makes
#' classification total: every address matches some row, so "globally
#' reachable ordinary unicast" becomes a statement backed by a registry row
#' rather than an inference from an absence.
#'
#' Classifying from the special-purpose registries alone is a known
#' CVE-producing pattern, and the clearest case is **multicast**: neither
#' special-purpose registry contains `224.0.0.0/4` or `ff00::/8` at all. A
#' table derived from them therefore has no multicast handling, which is how
#' `ssrfcheck` shipped CVE-2025-8267.
#'
#' @section Precedence, stated by the source:
#'
#' The special-purpose registries **outrank** these. That is not raddr's
#' judgment: the address-space registries themselves carry "For authoritative
#' registration, see \[Special-Purpose Address Space\]".
#'
#' Because these two are exact partitions, *every* special-purpose block falls
#' inside one of their rows, so precedence is not an edge case -- it decides
#' every lookup that matches both layers. Five prefixes appear in both pairs
#' **identically** (`0.0.0.0/8`, `10.0.0.0/8`, `127.0.0.0/8`, `fc00::/7`,
#' `fe80::/10`); for those the two layers agree and only the columns differ.
#'
#' @section No policy columns, and none invented:
#'
#' The five IANA policy logicals do not exist in these registries, so they are
#' absent here rather than filled in. The special-purpose registry answers
#' policy; the address-space registry answers identity; neither invents the
#' other's answer.
#'
#' What these carry instead is `status` (IPv4: `ALLOCATED`, `LEGACY` or
#' `RESERVED`; `NA` for IPv6, which has no such column), `date` (IPv4 only) and
#' `notes` (IPv6 only -- free prose, and the only record that `200::/7` and
#' `fec0::/10` are deprecated).
#'
#' `rfc` is `NA` for **every** IPv4 row, because that registry has no reference
#' column. The RFCs behind its rows live in numeric footnotes whose text is on
#' the registry page and not in the CSV, so raddr reports the marker in
#' `footnotes` and does not transcribe the citation.
#'
#' @return A data frame of 276 rows: 256 IPv4 and 20 IPv6.
#'
#' @seealso [addr_registry()] for the authoritative special-purpose layer, and
#'   [addr_address_space_version()] for this snapshot's own provenance.
#'
#' @examples
#' space <- addr_address_space()
#' nrow(space)
#'
#' # The multicast ranges that appear in no special-purpose registry
#' space[space$name == "Multicast", c("block", "status")]
#'
#' # The IPv6 side is 20 rows that tile the whole space
#' space[space$space == "v6", c("block", "name")]
#'
#' @export
addr_address_space <- function() {
  raddr_registry_data$space[address_space_public_columns]
}

#' Provenance of the bundled special-purpose registry snapshot
#'
#' `addr_registry_version()` reports the date IANA itself records having last
#' changed the vendored **special-purpose** registries.
#' `addr_registry_outdated()` says whether that is longer ago than `max_age`
#' days.
#'
#' These two answer for [addr_registry()] only. The address-space pair is
#' vendored from different files and stamped separately; see
#' [addr_address_space_version()]. For *which bytes* are installed rather than
#' how current they are, see [addr_registry_snapshot()].
#'
#' @section What the stamp is, and is not:
#'
#' The IANA CSVs carry no version field. The stamp is the page-level
#' `Last Updated` field from IANA's own registry page -- its editorial date --
#' read at build time and stored as ISO text.
#'
#' It is deliberately **not** the `Last-Modified` header the CSV is served with,
#' which earlier versions of raddr used. That header is a site **deploy**
#' timestamp: unrelated CSVs across different IANA registries are served with
#' the same timestamp to the second, and at least one IANA registry has been
#' edited months after the `Last-Modified` its own export still carries. For
#' this pair the two happen to agree; for the address-space pair they do not,
#' which is what settled the question. The served header is still recorded in
#' the package's internal metadata, because it is a fact about the fetch -- it
#' is simply not an answer to "when did IANA last change this".
#'
#' Content identity is tracked separately and exactly, by a sha256 per file and
#' by the single snapshot id [addr_registry_snapshot()] returns.
#' `data-raw/build-registry.R --check` compares content and never dates, so a
#' stamp that drifts for deploy reasons cannot make the staleness guard pass or
#' fail.
#'
#' @section Unknown is not fresh:
#'
#' When either half has no date, the snapshot has no date:
#' `addr_registry_version()` returns `NA` and `addr_registry_outdated()` returns
#' `TRUE`.
#'
#' That asymmetry is deliberate. A snapshot of unknown age is one you have no
#' evidence about, and treating no evidence as evidence of freshness is the one
#' failure mode a staleness check exists to prevent.
#'
#' That extends to the source of the date. Scraping a field out of upstream
#' markup can fail in several ways -- the field renamed, duplicated, emptied, or
#' reformatted -- and every one of them yields `NA` here rather than a guess.
#' That is what makes reading the editorial date acceptable at all: the mode it
#' fails in is the safe one.
#'
#' The stamp is also the **older** of the two halves, because a snapshot is only
#' as current as its stalest part. Both special-purpose registries currently
#' record the same editorial date, so the rule does no work for this pair; it
#' does for [addr_address_space_version()].
#'
#' @section No refresh:
#'
#' There is no `addr_registry_refresh()`. raddr performs no network access at
#' all: the registries change on a multi-year cadence and the whole vendored
#' payload is 29 KB, so shipping it outright is a cleaner claim than network
#' code that defaults to off. A stale snapshot is fixed by upgrading the
#' package.
#'
#' @param max_age Maximum acceptable age in days. Default 365.
#'
#' @return `addr_registry_version()` returns a length-1 `character`
#'   `"YYYY-MM-DD"` date, or `NA_character_` when the snapshot is undated.
#'   `addr_registry_outdated()` returns a length-1 `logical`, `TRUE` when the
#'   snapshot is older than `max_age` days **or** undated.
#'
#' @seealso [addr_registry()] for the data itself.
#'
#' @examples
#' addr_registry_version()
#' addr_registry_outdated()
#'
#' # An undated or overly old snapshot is reported, never assumed fresh
#' addr_registry_outdated(max_age = 0)
#'
#' @export
addr_registry_version <- function() {
  version <- raddr_registry_data$meta$version
  if (is.null(version)) NA_character_ else as.character(version)
}

#' @rdname addr_registry_version
#' @export
addr_registry_outdated <- function(max_age = 365) {
  if (!is.numeric(max_age) || length(max_age) != 1L || is.na(max_age)) {
    abort("`max_age` must be a single non-missing number.")
  }
  if (max_age < 0) {
    abort("`max_age` must not be negative.")
  }

  version <- addr_registry_version()
  if (is.na(version)) {
    return(TRUE)
  }

  stamped <- as.Date(version)
  if (is.na(stamped)) {
    return(TRUE)
  }

  as.numeric(Sys.Date() - stamped) > max_age
}

#' Provenance of the bundled address-space snapshot
#'
#' Reports the date IANA itself records having last changed the vendored
#' address-space registries. This is [addr_registry_version()]'s counterpart for
#' [addr_address_space()], and follows the same rules: IANA's page-level
#' `Last Updated` field, the older of the two halves, and `NA` rather than a
#' guess whenever the date cannot be read.
#'
#' @section Why this is stamped separately:
#'
#' The two pairs are different files from different registries, and one date
#' across both would make each half assert something about a table it says
#' nothing about -- the same reason the transition overlay carries its own
#' stamp (`addr_transition_version()`).
#'
#' The separation is not theoretical, and this is the pair that proves it. These
#' two registries carry editorial dates two weeks apart, `2025-10-10` and
#' `2025-10-23`, so the "older of the two halves" rule does real work here while
#' it is a no-op for the special-purpose pair.
#'
#' @section This pair is why the stamp is editorial:
#'
#' raddr used to stamp from the `Last-Modified` header the CSVs are served with.
#' For the special-purpose pair that header happens to match IANA's editorial
#' date. For these two it does not: they are served with `2025-10-09` and
#' `2025-10-11` against editorial dates of `2025-10-10` and `2025-10-23`, so
#' the header approach reported this snapshot as a day older than IANA says it
#' is, for reasons that have nothing to do with the data. Vendoring these two
#' turned that from a caveat into a wrong number, and the stamp now comes from
#' the registry page instead.
#'
#' @return A length-1 `character` `"YYYY-MM-DD"` date, or `NA_character_` when
#'   either half of the snapshot is undated.
#'
#' @seealso [addr_address_space()] for the data itself, and
#'   [addr_registry_snapshot()] for which bytes are installed.
#'
#' @examples
#' addr_address_space_version()
#'
#' @export
addr_address_space_version <- function() {
  version <- raddr_registry_data$meta$space_version
  if (is.null(version)) NA_character_ else as.character(version)
}

#' Content-addressed identity of the bundled registry snapshot
#'
#' Returns one string identifying exactly which vendored IANA bytes are
#' installed: a `"sha256:..."` digest over all four registry files. This is the
#' value to quote in a bug report, because it pins the data a result came from
#' without depending on the package version.
#'
#' @section What it answers, and what it does not:
#'
#' It answers **which bytes**. Two installations reporting the same id have the
#' same four files, byte for byte.
#'
#' It does **not** answer which of two snapshots is newer. A hash has no order.
#' Currency is what [addr_registry_version()] and
#' [addr_address_space_version()] report, and those two are deliberately
#' separate because they make claims about separate tables.
#'
#' One id covers all four files for that same reason inverted. A *date* spanning
#' both pairs would make each half assert currency for a table it says nothing
#' about; a content hash asserts only what is installed, which is a property of
#' the payload as a whole.
#'
#' @section How it is computed:
#'
#' A sha256 over a canonical manifest: one `"<key> sha256:<hex>"` line per
#' source, each terminated by a newline, in the fixed order `v4`, `v6`,
#' `v4_space`, `v6_space`, hashed as UTF-8 bytes.
#'
#' The order and the spelling are part of the definition rather than formatting,
#' which is what makes the id reproducible outside R -- the manifest is a byte
#' string anything can build from the installed CSVs and hash. The manifest is
#' also stored beside the id, and `data-raw/build-registry.R --check` verifies
#' both steps: that the manifest still describes the files on disk, and that the
#' id still follows from the manifest. Being content rather than dates, both
#' belong in that guard, which never compares dates.
#'
#' @return A length-1 `character` of the form `"sha256:"` followed by 64 hex
#'   digits, or `NA_character_` if the installed snapshot records no id.
#'
#' @seealso [addr_registry_version()] and [addr_address_space_version()] for
#'   currency rather than identity.
#'
#' @examples
#' addr_registry_snapshot()
#'
#' @export
addr_registry_snapshot <- function() {
  snapshot <- raddr_registry_data$meta$snapshot
  if (is.null(snapshot)) NA_character_ else as.character(snapshot)
}
