# The vendored IANA special-purpose registries.
# See docs/architecture.md sections 7 and 5.3.
#
# The data is generated by data-raw/build-registry.R into R/sysdata.rda. Nothing
# here reads a file, and nothing here touches the network: raddr ships the
# registry rather than fetching it, so that "performs no network access" is a
# property of the code and not of a default argument (section 7).

# The public columns. `w1`-`w4` are the matcher's storage, not part of the
# answer, so they stay internal and the exported table keeps the block text and
# prefix length -- the two forms a caller can actually read.
registry_public_columns <- c(
  "block", "space", "prefix_len", "name", "rfc",
  "allocation_date", "termination_date",
  "source", "destination", "forwardable", "globally_reachable",
  "reserved_by_protocol", "footnotes"
)

#' The bundled IANA special-purpose address registries
#'
#' Returns the two IANA special-purpose address registries as one data frame,
#' exactly as vendored. This is the table `addr_classify()` will match against.
#' (Not a link: `addr_classify()` arrives with the classification layer.)
#'
#' @section All five policy columns, never collapsed:
#'
#' IANA records five independent properties per block, and raddr surfaces all
#' five rather than reducing them to a single "is it private" flag.
#' `globally_reachable` **is** IANA's `Globally Reachable` column, per row, with
#' an RFC citation -- not a value raddr derives.
#'
#' Each is `logical`, and `NA` is a real answer with a real meaning: IANA
#' declined to give one. Two cases produce it.
#'
#' \describe{
#'   \item{The block is deprecated}{`192.88.99.0/24` and `2001:10::/28` carry a
#'     `termination_date` and no policy values at all.}
#'   \item{The answer depends on something the table cannot express}{Teredo
#'     (`2001::/32`) and 6to4 (`2002::/16`) are recorded as `N/A` for
#'     `globally_reachable`, because reachability follows the *embedded* IPv4
#'     address. That is what `addr_embedded_scope()` is for.}
#' }
#'
#' Reading either as `FALSE` would assert a policy IANA specifically withheld,
#' so raddr keeps them `NA`.
#'
#' @section Blocks, not rows:
#'
#' One row here is one prefix. That is not always one row upstream: the CSV
#' names two prefixes in a single record (`192.0.0.170/32, 192.0.0.171/32`),
#' and three records wrap across lines because they cite more than one RFC.
#' The vendored 25 + 25 records become **51 blocks**.
#'
#' @section Longest prefix, not first match:
#'
#' The registry contains deliberate carve-outs -- `192.0.0.9/32` and
#' `192.0.0.10/32` are globally reachable inside a `192.0.0.0/24` that is not.
#' Any lookup over this table must be longest-prefix-match.
#'
#' @section Footnotes:
#'
#' `footnotes` records which upstream footnote markers a row carried, as a
#' space-separated string, and is `""` when it carried none. The footnote
#' **text** is not in the CSV -- it lives on the registry page -- so raddr
#' reports that a caveat exists rather than inventing its wording.
#'
#' @return A data frame of 51 rows. See the sections above for the columns.
#'
#' @seealso [addr_registry_version()] for the snapshot's provenance.
#'
#' @examples
#' reg <- addr_registry()
#' nrow(reg)
#'
#' # The carve-out that forces longest-prefix matching
#' reg[startsWith(reg$block, "192.0.0."), c("block", "globally_reachable")]
#'
#' # The blocks whose reachability IANA declined to state
#' reg[is.na(reg$globally_reachable), c("block", "name", "termination_date")]
#'
#' @export
addr_registry <- function() {
  raddr_registry_data$blocks[registry_public_columns]
}

#' Provenance of the bundled registry snapshot
#'
#' `addr_registry_version()` reports when the vendored registries were last
#' changed upstream. `addr_registry_outdated()` says whether that is longer ago
#' than `max_age` days.
#'
#' @section Unknown is not fresh:
#'
#' The IANA CSVs carry no version field, so the stamp is the `Last-Modified`
#' date the two files were served with, normalized at build time. When either
#' half has no date, the snapshot has no date: `addr_registry_version()` returns
#' `NA` and `addr_registry_outdated()` returns `TRUE`.
#'
#' That asymmetry is deliberate. A snapshot of unknown age is one you have no
#' evidence about, and treating no evidence as evidence of freshness is the one
#' failure mode a staleness check exists to prevent.
#'
#' The stamp is also the **older** of the two halves, because a snapshot is only
#' as current as its stalest part.
#'
#' @section No refresh:
#'
#' There is no `addr_registry_refresh()`. raddr performs no network access at
#' all: the registries change on a multi-year cadence and the whole vendored
#' payload is 4.7 KB, so shipping it outright is a cleaner claim than network
#' code that defaults to off. A stale snapshot is fixed by upgrading the
#' package.
#'
#' @param max_age Maximum acceptable age in days. Default 365.
#'
#' @return `addr_registry_version()` returns a length-1 `character`
#'   `"YYYY-MM-DD"` date, or `NA_character_` when the snapshot is undated.
#'   `addr_registry_outdated()` returns a length-1 `logical`, `TRUE` when the
#'   snapshot is older than `max_age` days **or** undated.
#'
#' @seealso [addr_registry()] for the data itself.
#'
#' @examples
#' addr_registry_version()
#' addr_registry_outdated()
#'
#' # An undated or overly old snapshot is reported, never assumed fresh
#' addr_registry_outdated(max_age = 0)
#'
#' @export
addr_registry_version <- function() {
  version <- raddr_registry_data$meta$version
  if (is.null(version)) NA_character_ else as.character(version)
}

#' @rdname addr_registry_version
#' @export
addr_registry_outdated <- function(max_age = 365) {
  if (!is.numeric(max_age) || length(max_age) != 1L || is.na(max_age)) {
    abort("`max_age` must be a single non-missing number.")
  }
  if (max_age < 0) {
    abort("`max_age` must not be negative.")
  }

  version <- addr_registry_version()
  if (is.na(version)) {
    return(TRUE)
  }

  stamped <- as.Date(version)
  if (is.na(stamped)) {
    return(TRUE)
  }

  as.numeric(Sys.Date() - stamped) > max_age
}
