# The vendored IANA special-purpose registries.
# See docs/architecture.md sections 7 and 5.3.
#
# The data is generated by data-raw/build-registry.R into R/sysdata.rda. Nothing
# here reads a file, and nothing here touches the network: raddr ships the
# registry rather than fetching it, so that "performs no network access" is a
# property of the code and not of a default argument (section 7).

# The public columns. `w1`-`w4` are the matcher's storage, not part of the
# answer, so they stay internal and the exported table keeps the block text and
# prefix length -- the two forms a caller can actually read.
registry_public_columns <- c(
  "block", "space", "prefix_len", "name", "rfc",
  "allocation_date", "termination_date",
  "source", "destination", "forwardable", "globally_reachable",
  "reserved_by_protocol", "footnotes"
)

#' The bundled IANA special-purpose address registries
#'
#' Returns the two IANA special-purpose address registries as one data frame,
#' exactly as vendored. This is the table `addr_classify()` will match against.
#' (Not a link: `addr_classify()` arrives with the classification layer.)
#'
#' @section All five policy columns, never collapsed:
#'
#' IANA records five independent properties per block, and raddr surfaces all
#' five rather than reducing them to a single "is it private" flag.
#' `globally_reachable` **is** IANA's `Globally Reachable` column, per row, with
#' an RFC citation -- not a value raddr derives.
#'
#' Each is `logical`, and `NA` is a real answer with a real meaning: IANA
#' declined to give one. Two cases produce it.
#'
#' \describe{
#'   \item{The block is deprecated}{`192.88.99.0/24` and `2001:10::/28` carry a
#'     `termination_date` and no policy values at all.}
#'   \item{The answer depends on something the table cannot express}{Teredo
#'     (`2001::/32`) and 6to4 (`2002::/16`) are both recorded as `N/A` for
#'     `globally_reachable` -- but for **two different reasons**, carrying two
#'     different IANA footnotes. Do not merge them.}
#' }
#'
#' The two `N/A` reasons, kept apart because a reader following either
#' footnote must find the reason raddr states:
#'
#' \describe{
#'   \item{6to4 (`2002::/16`), footnote `[3]`, RFC 3056}{reachability follows
#'     the *embedded* IPv4 address, which a prefix table cannot express.}
#'   \item{Teredo (`2001::/32`), footnote `[2]`, RFC 4380 section 5}{a
#'     different thing entirely: relay advertisement is **voluntary and
#'     per-deployment**, so whether any given Teredo address is reachable
#'     depends on what its operator chose to advertise -- not on the embedded
#'     client address.}
#' }
#'
#' Reading either as `FALSE` would assert a policy IANA specifically withheld,
#' so raddr keeps them `NA`.
#'
#' @section Blocks, not rows:
#'
#' One row here is one prefix. That is not always one row upstream: the CSV
#' names two prefixes in a single record (`192.0.0.170/32, 192.0.0.171/32`),
#' and three records wrap across lines because they cite more than one RFC.
#' The vendored 25 + 25 records become **51 blocks**.
#'
#' @section Longest prefix, not first match:
#'
#' The registry contains deliberate carve-outs -- `192.0.0.9/32` and
#' `192.0.0.10/32` are globally reachable inside a `192.0.0.0/24` that is not.
#' Any lookup over this table must be longest-prefix-match.
#'
#' @section Footnotes:
#'
#' `footnotes` records which upstream footnote markers a row carried, as a
#' space-separated string, and is `""` when it carried none. The footnote
#' **text** is not in the CSV -- it lives on the registry page -- so raddr
#' reports that a caveat exists rather than inventing its wording.
#'
#' @return A data frame of 51 rows. See the sections above for the columns.
#'
#' @seealso [addr_registry_version()] for the snapshot's provenance.
#'
#' @examples
#' reg <- addr_registry()
#' nrow(reg)
#'
#' # The carve-out that forces longest-prefix matching
#' reg[startsWith(reg$block, "192.0.0."), c("block", "globally_reachable")]
#'
#' # The blocks whose reachability IANA declined to state
#' reg[is.na(reg$globally_reachable), c("block", "name", "termination_date")]
#'
#' @export
addr_registry <- function() {
  raddr_registry_data$blocks[registry_public_columns]
}

address_space_public_columns <- c(
  "block", "space", "prefix_len", "name", "rfc",
  "status", "date", "notes", "footnotes"
)

#' The bundled IANA address-space registries
#'
#' Returns the IANA IPv4 and IPv6 Address Space registries as one data frame,
#' exactly as vendored. This is the **fallback** layer: it answers what a range
#' is for and who holds it, for every address, including the ranges the
#' special-purpose registries never mention.
#'
#' @section Why a second pair of registries:
#'
#' Each of these two registries is an **exact partition** of its address space
#' -- 256 IPv4 `/8`s and 20 IPv6 blocks that tile `::/0` with no gap and no
#' overlap, asserted at build time. Together with [addr_registry()] that makes
#' classification total: every address matches some row, so "globally
#' reachable ordinary unicast" becomes a statement backed by a registry row
#' rather than an inference from an absence.
#'
#' Classifying from the special-purpose registries alone is a known
#' CVE-producing pattern, and the clearest case is **multicast**: neither
#' special-purpose registry contains `224.0.0.0/4` or `ff00::/8` at all. A
#' table derived from them therefore has no multicast handling, which is how
#' `ssrfcheck` shipped CVE-2025-8267.
#'
#' @section Precedence, stated by the source:
#'
#' The special-purpose registries **outrank** these. That is not raddr's
#' judgment: the address-space registries themselves carry "For authoritative
#' registration, see \[Special-Purpose Address Space\]".
#'
#' Because these two are exact partitions, *every* special-purpose block falls
#' inside one of their rows, so precedence is not an edge case -- it decides
#' every lookup that matches both layers. Five prefixes appear in both pairs
#' **identically** (`0.0.0.0/8`, `10.0.0.0/8`, `127.0.0.0/8`, `fc00::/7`,
#' `fe80::/10`); for those the two layers agree and only the columns differ.
#'
#' @section No policy columns, and none invented:
#'
#' The five IANA policy logicals do not exist in these registries, so they are
#' absent here rather than filled in. The special-purpose registry answers
#' policy; the address-space registry answers identity; neither invents the
#' other's answer.
#'
#' What these carry instead is `status` (IPv4: `ALLOCATED`, `LEGACY` or
#' `RESERVED`; `NA` for IPv6, which has no such column), `date` (IPv4 only) and
#' `notes` (IPv6 only -- free prose, and the only record that `200::/7` and
#' `fec0::/10` are deprecated).
#'
#' `rfc` is `NA` for **every** IPv4 row, because that registry has no reference
#' column. The RFCs behind its rows live in numeric footnotes whose text is on
#' the registry page and not in the CSV, so raddr reports the marker in
#' `footnotes` and does not transcribe the citation.
#'
#' @return A data frame of 276 rows: 256 IPv4 and 20 IPv6.
#'
#' @seealso [addr_registry()] for the authoritative special-purpose layer, and
#'   [addr_address_space_version()] for this snapshot's own provenance.
#'
#' @examples
#' space <- addr_address_space()
#' nrow(space)
#'
#' # The multicast ranges that appear in no special-purpose registry
#' space[space$name == "Multicast", c("block", "status")]
#'
#' # The IPv6 side is 20 rows that tile the whole space
#' space[space$space == "v6", c("block", "name")]
#'
#' @export
addr_address_space <- function() {
  raddr_registry_data$space[address_space_public_columns]
}

#' Provenance of the bundled special-purpose registry snapshot
#'
#' `addr_registry_version()` reports the date the vendored **special-purpose**
#' registry files were last **served** with. `addr_registry_outdated()` says
#' whether that is longer ago than `max_age` days.
#'
#' These two answer for [addr_registry()] only. The address-space pair is
#' vendored from different files and stamped separately; see
#' [addr_address_space_version()].
#'
#' @section What the stamp is, and is not:
#'
#' The IANA CSVs carry no version field, so the stamp is the `Last-Modified`
#' date the two files were served with, normalized at build time.
#'
#' That is a weaker signal than it looks, and the documentation used to
#' overstate it. `Last-Modified` is a site **deploy** timestamp rather than an
#' editorial one: unrelated CSVs across different IANA registries are served
#' with the same timestamp to the second, and at least one IANA registry has
#' been edited months after the `Last-Modified` its own CSV export still
#' carries. So the stamp answers "when was this file written to the server", not
#' "when did IANA last change this data".
#'
#' Content identity is tracked separately and exactly, by a sha256 per file
#' recorded at build time. `data-raw/build-registry.R --check` compares content
#' and never dates, so a stamp that drifts for deploy reasons cannot make the
#' staleness guard pass or fail.
#'
#' @section Unknown is not fresh:
#'
#' When either half has no date, the snapshot has no date:
#' `addr_registry_version()` returns `NA` and `addr_registry_outdated()` returns
#' `TRUE`.
#'
#' That asymmetry is deliberate. A snapshot of unknown age is one you have no
#' evidence about, and treating no evidence as evidence of freshness is the one
#' failure mode a staleness check exists to prevent.
#'
#' The stamp is also the **older** of the two halves, because a snapshot is only
#' as current as its stalest part. In practice the two halves are served with
#' the same deploy timestamp and the rule rarely bites; it is kept because it is
#' the right rule if they ever diverge, not because it is doing work today.
#'
#' @section No refresh:
#'
#' There is no `addr_registry_refresh()`. raddr performs no network access at
#' all: the registries change on a multi-year cadence and the whole vendored
#' payload is 29 KB, so shipping it outright is a cleaner claim than network
#' code that defaults to off. A stale snapshot is fixed by upgrading the
#' package.
#'
#' @param max_age Maximum acceptable age in days. Default 365.
#'
#' @return `addr_registry_version()` returns a length-1 `character`
#'   `"YYYY-MM-DD"` date, or `NA_character_` when the snapshot is undated.
#'   `addr_registry_outdated()` returns a length-1 `logical`, `TRUE` when the
#'   snapshot is older than `max_age` days **or** undated.
#'
#' @seealso [addr_registry()] for the data itself.
#'
#' @examples
#' addr_registry_version()
#' addr_registry_outdated()
#'
#' # An undated or overly old snapshot is reported, never assumed fresh
#' addr_registry_outdated(max_age = 0)
#'
#' @export
addr_registry_version <- function() {
  version <- raddr_registry_data$meta$version
  if (is.null(version)) NA_character_ else as.character(version)
}

#' @rdname addr_registry_version
#' @export
addr_registry_outdated <- function(max_age = 365) {
  if (!is.numeric(max_age) || length(max_age) != 1L || is.na(max_age)) {
    abort("`max_age` must be a single non-missing number.")
  }
  if (max_age < 0) {
    abort("`max_age` must not be negative.")
  }

  version <- addr_registry_version()
  if (is.na(version)) {
    return(TRUE)
  }

  stamped <- as.Date(version)
  if (is.na(stamped)) {
    return(TRUE)
  }

  as.numeric(Sys.Date() - stamped) > max_age
}

#' Provenance of the bundled address-space snapshot
#'
#' Reports the date the vendored IANA address-space files were last **served**
#' with, normalized to ISO at build time. This is [addr_registry_version()]'s
#' counterpart for [addr_address_space()].
#'
#' @section Why this is stamped separately:
#'
#' The two pairs are different files from different registries, and one date
#' across both would make each half assert something about a table it says
#' nothing about -- the same reason the transition overlay carries its own
#' stamp (`addr_transition_version()`).
#'
#' The separation is not theoretical here. The four vendored files are **not**
#' served with one timestamp: three carry `Thu, 09 Oct 2025 21:51:16 GMT` and
#' the IPv6 address-space export carries `Sat, 11 Oct 2025 00:06:16 GMT`. So
#' the "older of the two halves" rule, which is a no-op for the special-purpose
#' pair, actually does work for this one.
#'
#' The same caveat applies as to [addr_registry_version()], and more strongly:
#' `Last-Modified` is a site **deploy** timestamp, not an editorial one. For
#' the special-purpose pair the served date happens to match IANA's own page
#' level `Last Updated`. For these two it does not, so this stamp answers
#' "when was this file written to the server" and nothing more. Content
#' identity is tracked exactly and separately, by a sha256 per file.
#'
#' @return A length-1 `character` `"YYYY-MM-DD"` date, or `NA_character_` when
#'   either half of the snapshot is undated.
#'
#' @seealso [addr_address_space()] for the data itself.
#'
#' @examples
#' addr_address_space_version()
#'
#' @export
addr_address_space_version <- function() {
  version <- raddr_registry_data$meta$space_version
  if (is.null(version)) NA_character_ else as.character(version)
}
